// The whole of https://perch-cli.github.io/perch/ — the splash front page, the
// guide, and the two installers `public/` carries to the root of the output
// (ADR one-thing-renders-the-site).
//
// TypeScript rather than JavaScript for a reason this file is the best example
// of: a mistyped key here builds cleanly and serves a site that is wrong — a
// sidebar autogenerated from nothing, a `base` that does not match where Pages
// serves from.
import starlight from "@astrojs/starlight";
import { satteri } from "@astrojs/markdown-satteri";
import { defineConfig, passthroughImageService } from "astro/config";
import { rewriteGuideLinks } from "./src/plugins/guide-links";

// Said once: it is `base` below, and it is the prefix the guide's relative
// markdown links are rewritten onto.
const base = "/perch";

export default defineConfig({
  // Both halves have to be said, and they are not the same thing. `site` is what
  // absolute URLs — the sitemap, the canonical tags — are built from; `base` is
  // the prefix every path carries, because this repository is served from a
  // subdirectory of the organization's domain rather than from a root of its own.
  site: "https://perch-cli.github.io",
  base,
  // Sätteri is Astro's own pipeline and its default; naming it here is what gives
  // it a plugin, and `markdown.rehypePlugins` is the deprecated way to do this.
  markdown: { processor: satteri({ hastPlugins: [rewriteGuideLinks({ base })] }) },
  // Every image on this site is the one SVG below, and Astro's default image
  // service would want Sharp — a native dependency, in the deploy path that
  // publishes the installers — to resize a vector it cannot improve.
  image: { service: passthroughImageService() },
  integrations: [
    starlight({
      title: "Perch",
      description:
        "Run Claude Code as whichever Claude account you want, without going through the login flow again.",
      // The app icon, where it already lives. Copying it here would be a second
      // source for one file.
      logo: { src: "../docs/assets/icon.svg" },
      // Starlight's default, said out loud because this one is not a file in
      // `public/`: `src/pages/favicon.svg.ts` is the route that serves it, and
      // the default left implicit is what shows a tab a broken image.
      favicon: "/favicon.svg",
      customCss: ["./src/styles/perch.css"],
      // Starlight declares a large-image card by default, and this site carries
      // no og:image — that pairing renders an oversized empty slot on every
      // shared link. `summary` is the card the head can honestly fill.
      head: [
        {
          tag: "meta",
          attrs: { name: "twitter:card", content: "summary" },
        },
      ],
      // Both exist for the client-side router: one to put `<ClientRouter />` in
      // the head, one to keep the search dialog across a swap.
      components: {
        Head: "./src/components/Head.astro",
        Search: "./src/components/Search.astro",
      },
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/perch-cli/perch",
        },
      ],
      // Starlight appends the page's path within the project, so this ends up at
      // `…/edit/main/pages/src/content/docs/<page>.md` — the markdown, on the
      // branch a fix is made on rather than the tag the guide is published from.
      editLink: {
        baseUrl: "https://github.com/perch-cli/perch/edit/main/pages/",
      },
      // A transcript is most of what these pages are, and a sentence cut off at
      // the right edge of a box is one nobody reads.
      expressiveCode: {
        defaultProps: { wrap: true },
      },
    }),
  ],
});
