// The whole of https://perch-cli.github.io/perch/ — the splash front page, the
// guide, and the two installers `public/` carries to the root of the output
// (ADR one-thing-renders-the-site).
//
// TypeScript rather than JavaScript for a reason this file is the best example
// of: a mistyped key here builds cleanly and serves a site that is wrong — a
// sidebar autogenerated from nothing, a `base` that does not match where Pages
// serves from.
import starlight from "@astrojs/starlight";
import { satteri } from "@astrojs/markdown-satteri";
import { defineConfig, passthroughImageService } from "astro/config";
import { rewriteGuideLinks } from "./src/plugins/guide-links";

// Said once: it is `base` below, and it is the prefix the guide's relative
// markdown links are rewritten onto.
const base = "/perch";
const site = "https://perch-cli.github.io";
// Where the site is, with the slash a fetcher of `og:image` cannot resolve for
// itself.
const root = `${site}${base}/`;

export default defineConfig({
  // Both halves have to be said, and they are not the same thing. `site` is what
  // absolute URLs — the sitemap, the canonical tags — are built from; `base` is
  // the prefix every path carries, because this repository is served from a
  // subdirectory of the organization's domain rather than from a root of its own.
  site,
  base,
  // Sätteri is Astro's own pipeline and its default; naming it here is what gives
  // it a plugin, and `markdown.rehypePlugins` is the deprecated way to do this.
  markdown: { processor: satteri({ hastPlugins: [rewriteGuideLinks({ base })] }) },
  // Every image on this site is the one SVG below, and Astro's default image
  // service would want Sharp — a native dependency, in the deploy path that
  // publishes the installers — to resize a vector it cannot improve.
  image: { service: passthroughImageService() },
  integrations: [
    starlight({
      title: "Perch",
      description:
        "Run Claude Code as whichever Claude account you want, without going through the login flow again.",
      // The app icon, where it already lives. Copying it here would be a second
      // source for one file.
      logo: { src: "../docs/assets/icon.svg" },
      // Starlight's default, said out loud because this one is not a file in
      // `public/`: `src/pages/favicon.svg.ts` is the route that serves it, and
      // the default left implicit is what shows a tab a broken image.
      favicon: "/favicon.svg",
      customCss: ["./src/styles/perch.css"],
      // What Starlight leaves out and a crawler asks for: the icon as PNG and
      // ICO for Google and iOS, a manifest for Android, the card a shared link
      // shows. Every path is `base`-prefixed by hand, because a `head` entry is
      // emitted as written.
      head: [
        { tag: "link", attrs: { rel: "icon", href: `${base}/favicon.ico`, sizes: "any" } },
        {
          tag: "link",
          attrs: {
            rel: "icon",
            type: "image/png",
            sizes: "32x32",
            href: `${base}/favicon-32x32.png`,
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "apple-touch-icon",
            sizes: "180x180",
            href: `${base}/apple-touch-icon.png`,
          },
        },
        { tag: "link", attrs: { rel: "manifest", href: `${base}/site.webmanifest` } },
        { tag: "meta", attrs: { property: "og:image", content: `${root}og.png` } },
        { tag: "meta", attrs: { property: "og:image:width", content: "1200" } },
        { tag: "meta", attrs: { property: "og:image:height", content: "630" } },
        { tag: "meta", attrs: { property: "og:image:alt", content: "The Perch icon" } },
        { tag: "meta", attrs: { name: "twitter:image", content: `${root}og.png` } },
        // Starlight's own backgrounds, one per theme. Two entries survive
        // Starlight's merge, which only drops a default a user entry matches.
        {
          tag: "meta",
          attrs: {
            name: "theme-color",
            media: "(prefers-color-scheme: light)",
            content: "#ffffff",
          },
        },
        {
          tag: "meta",
          attrs: { name: "theme-color", media: "(prefers-color-scheme: dark)", content: "#17181c" },
        },
      ],
      // Both exist for the client-side router: one to put `<ClientRouter />` in
      // the head, one to keep the search dialog across a swap.
      components: {
        Head: "./src/components/Head.astro",
        Search: "./src/components/Search.astro",
      },
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/perch-cli/perch",
        },
      ],
      // Starlight appends the page's path within the project, so this ends up at
      // `…/edit/main/pages/src/content/docs/<page>.md` — the markdown, on the
      // branch a fix is made on rather than the tag the guide is published from.
      editLink: {
        baseUrl: "https://github.com/perch-cli/perch/edit/main/pages/",
      },
      // A transcript is most of what these pages are, and a sentence cut off at
      // the right edge of a box is one nobody reads.
      expressiveCode: {
        defaultProps: { wrap: true },
      },
    }),
  ],
});
