import starlight from "@astrojs/starlight";
import { satteri } from "@astrojs/markdown-satteri";
import { defineConfig, passthroughImageService } from "astro/config";
import { rewriteGuideLinks } from "./src/plugins/guide-links";

// Where GitHub Pages serves this repository from, said once: it is `base` below,
// and it is the prefix the guide's relative markdown links are rewritten onto.
const base = "/perch";

// The whole of https://perch-cli.github.io/perch/ — the splash front page, the
// guide, and the two installers `public/` carries to the root of the output
// (ADR 0062). One project rather than two artifacts sharing an accent color.
//
// TypeScript rather than JavaScript for a reason this file is the best example
// of: a mistyped key here builds cleanly and serves a site that is wrong — a
// sidebar autogenerated from nothing, a `base` that does not match where Pages
// serves from.
export default defineConfig({
  // Both halves have to be said, and they are not the same thing. `site` is what
  // absolute URLs — the sitemap, the canonical tags — are built from; `base` is
  // the prefix every path on the site carries, because this repository is served
  // from a subdirectory of the organization's domain rather than from a root of
  // its own.
  site: "https://perch-cli.github.io",
  base,
  // The guide's cross-references are relative markdown paths, because the guide
  // is read on GitHub too. This is what turns them into paths this site serves.
  // Sätteri is Astro's own pipeline and its default; naming it here is what gives
  // it a plugin, and `markdown.rehypePlugins` is the deprecated way to do this.
  markdown: { processor: satteri({ hastPlugins: [rewriteGuideLinks({ base })] }) },
  // Every image on this site is the one SVG below, and Astro's default image
  // service would want Sharp — a native dependency, in the deploy path that
  // publishes the installers — to resize a vector it cannot improve.
  image: { service: passthroughImageService() },
  integrations: [
    starlight({
      title: "Perch",
      description:
        "Run Claude Code as whichever Claude account you want, without going through the login flow again.",
      // The app icon, where it already lives. Copying it here would be a second
      // source for one file, and the guide moving was enough movement for one
      // change.
      logo: { src: "../docs/assets/icon.svg" },
      customCss: ["./src/styles/perch.css"],
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/perch-cli/perch",
        },
      ],
      // Starlight appends the page's path within the project, so this ends up at
      // `…/edit/main/pages/src/content/docs/<page>.md` — the markdown, on the
      // branch the site deploys from.
      editLink: {
        baseUrl: "https://github.com/perch-cli/perch/edit/main/pages/",
      },
      // No `sidebar` here on purpose: without one Starlight generates it from
      // the pages that exist, so it cannot omit a page the way `SUMMARY.md`
      // could. The order is `sidebar.order` in each page's frontmatter, which is
      // the one thing the file system does not know.
      //
      // A transcript is most of what these pages are, and the lines Perch prints
      // are sentences: a sentence cut off at the right edge of a box is one
      // nobody reads. So they wrap rather than scroll.
      expressiveCode: {
        defaultProps: { wrap: true },
      },
    }),
  ],
});
