#!/bin/sh
# Writes the Homebrew formula for one Release to stdout.
#
#   packaging/homebrew/formula.sh <version-without-v> <path-to-SHA256SUMS>
#
# The checksums come from the SHA256SUMS the Release published rather than from a
# recomputation, so the formula can only point at bytes on the Release page. A
# binary formula rather than a source one, which would put a Rust toolchain in
# front of every `brew install perch` (ADR this-repo-assembles-a-release).

set -eu

if [ $# -ne 2 ]; then
    echo "usage: $0 <version> <SHA256SUMS>" >&2
    exit 1
fi

version="$1"
sums="$2"

hash_for() {
    archive="perch-v${version}-$1.tar.gz"
    hash=$(awk -v f="$archive" '$2 == f { print $1 }' "$sums")
    if [ -z "$hash" ]; then
        echo "no checksum for $archive in $sums" >&2
        exit 1
    fi
    printf '%s' "$hash"
}

# Read every one before writing anything, so a missing archive fails with a
# message rather than half a formula.
darwin_arm=$(hash_for aarch64-apple-darwin)
darwin_intel=$(hash_for x86_64-apple-darwin)
linux_arm=$(hash_for aarch64-unknown-linux-musl)
linux_intel=$(hash_for x86_64-unknown-linux-musl)

base="https://github.com/perch-cli/perch/releases/download/v${version}"

cat <<FORMULA
# Generated by packaging/homebrew/formula.sh. Do not edit by hand: every
# release overwrites this file.
class Perch < Formula
  desc "Run Claude Code as whichever Claude account you want, without logging in again"
  homepage "https://github.com/perch-cli/perch"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "${base}/perch-v${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${darwin_arm}"
    end

    on_intel do
      url "${base}/perch-v${version}-x86_64-apple-darwin.tar.gz"
      sha256 "${darwin_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/perch-v${version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${linux_arm}"
    end

    on_intel do
      url "${base}/perch-v${version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "perch"
  end

  test do
    assert_match "perch #{version}", shell_output("#{bin}/perch --version")
  end
end
FORMULA
